dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - opengsn/gsn@2.0.0
  - GNSPS/solidity-bytes-utils@0.1.1

autofetch_sources: true

compiler:
  solc:
    version: 0.6.9
    remappings:
      - "@opengsn/gsn=opengsn/gsn@2.0.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - "@openzeppelin/contracts-ethereum-package=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@openzeppelin/contracts-ethereum-package-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0"
      - "@gnsps/solidity-bytes-utils=GNSPS/solidity-bytes-utils@0.1.1"

# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      unlock:
        - 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045